apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-k8s-redhat-linux
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dk-k8s-redhat-linux
  template:
    metadata:
      labels:
        app: dk-k8s-redhat-linux
    spec:
      securityContext:
        fsGroup: 1000   # 👈 THIS FIXES PERMISSION
      containers:
      - name: dk-k8s-redhat-linux
        securityContext:
          runAsUser: 1000
        image: avadhut18/dk-k8s-redhat-linux:v1
        # 🔹 Environment Variables
        env:
        - name: MY_ENV
          value: "Hello_From_Kubernetes"

        # 🔹 Arguments
        args:
        - "--myArg=Hello_From_Args"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: /app/data
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: file-pvc
      