apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-k8s-redhat-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-k8s-redhat-linux
  template:
    metadata:
      labels:
        app: dk-k8s-redhat-linux
    spec:
      containers:
      - name: dk-k8s-redhat-linux
        image: avadhut18/dk-k8s-redhat-linux:v1 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: /app/data
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: file-pvc